return function(t)
	local git = require("core-git")
	t.deep_eq(git.current_branch_args(), { "branch", "--show-current" }, "current branch command")
	t.deep_eq(git.upstream_args(), { "rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{upstream}" }, "upstream command")
	t.deep_eq(git.branch_list_args(true), { "branch", "--all", "--format=%(refname:short)%09%(HEAD)%09%(upstream:short)%09%(upstream:trackshort)%09%(refname)" }, "branch list command")
	t.deep_eq(git.push_args(nil, nil, false), { "push" }, "plain push never adds unsafe flags")
	t.deep_eq(git.push_args("origin", "main", true), { "push", "--set-upstream", "origin", "main" }, "upstream push")
	t.deep_eq(git.create_branch_args("feature/a", "main", false), { "branch", "feature/a", "main" }, "branch create")
	t.deep_eq(git.create_branch_args("feature/a", nil, true), { "switch", "-c", "feature/a" }, "create and switch")
	t.deep_eq(git.rename_branch_args(nil, "new"), { "branch", "-m", "new" }, "rename current branch")
	t.deep_eq(git.delete_branch_args("old"), { "branch", "-d", "old" }, "safe branch delete")
	t.deep_eq(git.switch_branch_args("origin/feature", "origin/feature", nil), { "switch", "--track", "origin/feature" }, "track remote branch")
	t.falsy(git.validate_name_input("@{-1}"), "relative branch syntax is rejected")
	t.falsy(git.validate_name_input("-bad"), "leading dash is rejected")
	t.truthy(git.validate_name_input("feature/good"), "ordinary branch name is accepted")
	local branches = git.parse_branches("main\t*\torigin/main\t[origin/main]\trefs/heads/main\norigin/feature\t\t\t\trefs/remotes/origin/feature\nfeature/local\t\torigin/feature\t[origin/feature]\trefs/heads/feature/local\n")
	t.eq(branches[1].current, true, "current branch parsed")
	t.eq(branches[1].upstream, "origin/main", "upstream parsed")
	t.eq(branches[2].remote, true, "remote branch parsed")
	t.falsy(branches[3].remote, "local slash branch is not remote")
	t.eq(git.find_branch(branches, "feature/local").tracking, "[origin/feature]", "tracking parsed")
	t.deep_eq(git.parse_lines(" origin\n\nupstream \n"), { "origin", "upstream" }, "line list parser")
end
