return function(t)
	local c = require("core-commands")
	t.deep_eq(c.git_update(), { "pull", "--ff-only" }, "git update is fast-forward only")
	t.deep_eq(c.svn_update(nil), { "update" }, "svn update defaults to the working copy")
	t.deep_eq(c.git_commit("/tmp/msg", { "a.txt" }, "paths"), { "commit", "--file=/tmp/msg", "--", "a.txt" }, "git path commit")
	t.deep_eq(c.git_commit("/tmp/msg", { "a.txt" }, "staged"), { "commit", "--file=/tmp/msg" }, "git staged commit")
	t.deep_eq(c.svn_commit("/tmp/msg", { "日本語.txt", "a b.txt" }), { "commit", "--file=/tmp/msg", "--", "日本語.txt", "a b.txt" }, "svn commit keeps argument boundaries")
	t.deep_eq(c.git_diff({ "a b.txt" }), { "--no-pager", "diff", "--", "a b.txt" }, "git diff disables Git's pager")
	t.deep_eq(c.git_diff({}), { "--no-pager", "diff" }, "repository diff has no path filter")
	t.deep_eq(c.svn_diff({ "." }), { "diff", "--", "." }, "svn diff")
	t.deep_eq(c.git_log({ "src" }), { "--no-pager", "log", "--decorate", "--oneline", "--graph", "--", "src" }, "git targeted log disables Git's pager")
	t.deep_eq(c.git_log({}), { "--no-pager", "log", "--decorate", "--oneline", "--graph", "--all" }, "git repository log disables Git's pager")
	t.deep_eq(c.svn_log({}), { "log" }, "repository SVN log has no path filter")
	t.deep_eq(c.svn_discard({ "src" }, true), { "revert", "--depth=infinity", "--", "src" }, "svn recursive discard")
	t.deep_eq(c.git_discard({ "a.txt" }), { "restore", "--", "a.txt" }, "git discard")
	t.deep_eq(c.git_add({ "a.txt", "b.txt" }), { "add", "--", "a.txt", "b.txt" }, "git add")
	t.deep_eq(c.svn_add({ "日本語.txt" }), { "add", "--", "日本語.txt" }, "svn add keeps argument boundaries")
end
