return function(t)
	local c = require("core-commands")
	t.deep_eq(c.git_update(), { "pull", "--ff-only" }, "git update is fast-forward only")
	t.deep_eq(c.svn_update(nil), { "update" }, "svn update defaults to the working copy")
	t.deep_eq(c.git_commit("/tmp/msg", { "a.txt" }, "paths"), { "commit", "--file=/tmp/msg", "--", "a.txt" }, "git path commit")
	t.deep_eq(c.git_commit("/tmp/msg", { "a.txt" }, "staged"), { "commit", "--file=/tmp/msg" }, "git staged commit")
	t.deep_eq(c.svn_commit("/tmp/msg", { "日本語.txt", "a b.txt" }), { "commit", "--file=/tmp/msg", "--", "日本語.txt", "a b.txt" }, "svn commit keeps argument boundaries")
	t.deep_eq(c.git_diff({ "a b.txt" }), { "diff", "--", "a b.txt" }, "git diff")
	t.deep_eq(c.svn_diff({ "." }), { "diff", "--", "." }, "svn diff")
	t.deep_eq(c.git_log({ "src" }), { "log", "--decorate", "--oneline", "--graph", "--", "src" }, "git targeted log")
	t.deep_eq(c.git_log({}), { "log", "--decorate", "--oneline", "--graph", "--all" }, "git repository log")
	t.deep_eq(c.svn_discard({ "src" }, true), { "revert", "--depth=infinity", "--", "src" }, "svn recursive discard")
	t.deep_eq(c.git_discard({ "a.txt" }), { "restore", "--", "a.txt" }, "git discard")
end
